import React, { useState, useEffect } from 'react';
import { View, Text, TouchableOpacity, Modal, ActivityIndicator, FlatList, ScrollView } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useSnippets } from '../hooks/useSnippets';
import { Snippet } from '../types';
import { useRoute, useRouter } from 'expo-router';

export default function SnippetDetailsScreen() {
  const route = useRoute<{ snippetId: string }>();
  const { snippets, toggleFavorite } = useSnippets();
  const router = useRouter();
  const [snippet, setSnippet] = useState<Snippet | null>(null);
  const [loading, setLoading] = useState(true);
  const [showExplanation, setShowExplanation] = useState(false);
  const [explanation, setExplanation] = useState<string>('');

  useEffect(() => {
    const loadSnippet = async () => {
      try {
        setLoading(true);
        const snippetFromList = snippets.find(s => s.id === route.params.snippetId);
        if (snippetFromList) {
          setSnippet(snippetFromList);
        } else {
          // If not found in the list (maybe not loaded yet), we could fetch from DB directly
          // For simplicity, we'll assume it's in the list
          setSnippet(null);
        }
      } catch (err) {
        console.error('Error loading snippet:', err);
        setSnippet(null);
      } finally {
        setLoading(false);
      }
    };

    loadSnippet();
  }, [route.params.snippetId, snippets]);

  if (loading) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <ActivityIndicator size="large" />
      </View>
    );
  }

  if (!snippet) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Snippet not found</Text>
        <TouchableOpacity onPress={() => router.back()}>
          <Text>Go back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <View style={{ flex: 1 }}>
      <ScrollView contentContainerStyle={{ padding: 16 }}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <Text style={{ fontSize: 20, fontWeight: 'bold' }}>{snippet.title}</Text>
          <TouchableOpacity onPress={() => toggleFavorite(snippet.id)}>
            <Feather name={snippet.isFavorite ? 'star' : 'star-outline'} size={24} color={snippet.isFavorite ? '#ffd700' : '#ccc'} />
          </TouchableOpacity>
        </View>

        <Text style={{ fontWeight: 'bold', marginBottom: 8 }}>Language:</Text>
        <Text>{snippet.language}</Text>

        <Text style={{ fontWeight: 'bold', marginVertical: 8 }}>Tags:</Text>
        <View style={{ flexWrap: 'row', marginBottom: 16 }}>
          {snippet.tags.map((tag, index) => (
            <TouchableOpacity
              key={index}
              style={{
                backgroundColor: '#eee',
                paddingHorizontal: 12,
                paddingVertical: 6,
                borderRadius: 12,
                marginRight: 8,
                marginBottom: 8,
              }}
            >
              <Text>{tag}</Text>
            </TouchableOpacity>
          ))}
        </View>

        <Text style={{ fontWeight: 'bold', marginBottom: 8 }}>Code:</Text>
        <Text style={{
          backgroundColor: '#f8f8f8',
          padding: 12,
          borderRadius: 4,
          fontFamily: 'monospace',
          whiteSpace: 'pre-wrap',
        }}>{snippet.code}</Text>

        <View style={{ marginTop: 24 }}>
          <TouchableOpacity onPress={() => setShowExplanation(true)} style={{
            backgroundColor: '#007AFF',
            paddingVertical: 12,
            borderRadius: 4,
            alignItems: 'center',
          }}>
            <Text style={{ color: 'white', fontWeight: 'bold' }}>Explain Code</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>

      {/* Explanation Modal */}
      <Modal visible={showExplanation} transparent={true} animationType="fade">
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)' }}>
          <View style={{ backgroundColor: 'white', padding: 24, borderRadius: 8, width: '80%' }}>
            <TouchableOpacity onPress={() => setShowExplanation(false)} style={{ alignSelf: 'flex-end', marginBottom: 12 }}>
              <Feather name="x" size={20} color="#666" />
            </TouchableOpacity>
            <Text style={{ fontSize: 18, fontWeight: 'bold', marginBottom: 12 }}>Code Explanation</Text>
            <Text style={{ color: '#666', marginBottom: 12 }}>
              {/* In a real app, this would be generated by an AI service */}
              This is a placeholder for the AI-generated explanation of the code snippet.
              The explanation would include what the code does, how it works, and potential improvements.
            </Text>
            <TouchableOpacity onPress={() => setShowExplanation(false)} style={{
              backgroundColor: '#007AFF',
              paddingVertical: 8,
              borderRadius: 4,
              alignItems: 'center',
            }}>
              <Text style={{ color: 'white' }}>Close</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </View>
  );
}